// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWL-0RYhZaNslZP6z2BK58qx8tG9LiLg0',
    appId: '1:27647146706:web:ac733c97e87f73597bcb0b',
    messagingSenderId: '27647146706',
    projectId: 'rfidsample-c13cc',
    authDomain: 'rfidsample-c13cc.firebaseapp.com',
    databaseURL: 'https://rfidsample-c13cc-default-rtdb.firebaseio.com',
    storageBucket: 'rfidsample-c13cc.appspot.com',
    measurementId: 'G-V22CYS6D82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlQhPYoebrZkWt4G3YVSjTA8hQHWIEnbM',
    appId: '1:27647146706:android:f3538a46071ac76a7bcb0b',
    messagingSenderId: '27647146706',
    projectId: 'rfidsample-c13cc',
    databaseURL: 'https://rfidsample-c13cc-default-rtdb.firebaseio.com',
    storageBucket: 'rfidsample-c13cc.appspot.com',
  );
}
